title: "MTG News"
description: "Daily blog posts about Magic: The Gathering news."
theme: "jekyll-theme-minimal"
baseurl: "/mtg-news"   # Important for project sites
permalink: /:year/:month/:day/:title.html



